site_name: DjangoDoo
site_url: https://github.com/MehediMK/DjangoDoo-docs
repo_name: 'DjangoDoo-docs'
site_author: 'Mehedi Khan'
site_favicon: assets/logo.png

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Modules Guide: modules.md
  - Contributing: contributing.md
  - FAQ: faq.md
  - 🐧: https://github.com/MehediMK/djangodoo

theme:
  name: mkdocs
  
  logo: images/logo.png
  
  nav_style: danger
  sticky_navigation: True

  analytics:
    gtag: G-R8QSGZSXY6
    anonymize_ip: True
  
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

  color_mode: auto
  user_color_mode_toggle: true

plugins:
  - search:
      indexing: 'full'

extra:
  version: 0.0.1
  generator: false

copyright: Copyright &copy; 2024 - 2025 MehediMK(DjangoDoo)